//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Time_Tag_Participant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesTagTime : DbContext
    {
        public EntitiesTagTime()
            : base("name=EntitiesTagTime")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<Start_List> Start_List { get; set; }
        public virtual DbSet<Tag_Number> Tag_Number { get; set; }
        public virtual DbSet<Time_Registration> Time_Registration { get; set; }
        public virtual DbSet<VStartingLists> VStartingLists { get; set; }
        public virtual DbSet<Zawodnik> Zawodnik { get; set; }
        public virtual DbSet<vResultList> vResultList { get; set; }
    }
}
