//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Time_Tag_Participant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag_Number
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tag_Number()
        {
            this.Zawodnik = new HashSet<Zawodnik>();
        }
    
        public int tag_id { get; set; }
        public string tag_IdNumber { get; set; }
        public Nullable<int> tag_LabelNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zawodnik> Zawodnik { get; set; }
    }
}
