//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Time_Tag_Participant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time_Registration
    {
        public int time_id { get; set; }
        public Nullable<System.DateTime> time_registration1 { get; set; }
        public Nullable<int> zaw_id { get; set; }
        public Nullable<int> time_counter { get; set; }
    
        public virtual Zawodnik Zawodnik { get; set; }
    }
}
