//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Time_Tag_Participant
{
    using System;
    using System.Collections.Generic;
    
    public partial class vResultList
    {
        public int kart_id { get; set; }
        public int dys_id { get; set; }
        public int tag_id { get; set; }
        public string kart_nazwisko { get; set; }
        public int zaw_id { get; set; }
        public string kart_imie { get; set; }
        public string dys_wartosc { get; set; }
        public string dane { get; set; }
        public string suma_czas { get; set; }
        public Nullable<int> sum_seconds { get; set; }
        public int rzeczywistaIloscOdbic { get; set; }
        public Nullable<int> tag_LabelNumber { get; set; }
        public Nullable<int> iloscOdbic { get; set; }
        public string realDistance { get; set; }
    }
}
