//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Time_Tag_Participant
{
    using System;
    using System.Collections.Generic;
    
    public partial class VStartingLists
    {
        public Nullable<long> Id { get; set; }
        public string list_nazwa { get; set; }
        public Nullable<System.DateTime> list_data { get; set; }
        public Nullable<System.TimeSpan> list_czas { get; set; }
        public Nullable<int> list_ilosc { get; set; }
        public int list_id { get; set; }
        public string kart_nazwisko { get; set; }
        public string kart_imie { get; set; }
        public Nullable<int> tag_LabelNumber { get; set; }
        public string dys_wartosc { get; set; }
    }
}
