//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Time_Tag_Participant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawodnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zawodnik()
        {
            this.Result = new HashSet<Result>();
            this.Time_Registration = new HashSet<Time_Registration>();
        }
    
        public int zaw_id { get; set; }
        public Nullable<bool> zaw_aktywny { get; set; }
        public Nullable<int> kartoteka_id { get; set; }
        public Nullable<int> list_id { get; set; }
        public Nullable<int> tag_id { get; set; }
        public Nullable<int> time_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }
        public virtual Start_List Start_List { get; set; }
        public virtual Tag_Number Tag_Number { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Time_Registration> Time_Registration { get; set; }
    }
}
