//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administratorzy
    {
        public int reg_id { get; set; }
        public string reg_imie { get; set; }
        public string reg_nazwisko { get; set; }
        public string reg_login { get; set; }
        public string reg_password { get; set; }
        public Nullable<bool> reg_aktywne { get; set; }
    }
}
