//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Registration_Participant_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dystans_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dystans_info()
        {
            this.Dystans = new HashSet<Dystans>();
        }
    
        public int info_id { get; set; }
        public string info_start_time { get; set; }
        public string info_start_date { get; set; }
        public string info_oplata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dystans> Dystans { get; set; }
    }
}
