//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Registration_Participant_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VmodelExt
    {
        public int dys_id { get; set; }
        public string kart_imie { get; set; }
        public string kart_nazwisko { get; set; }
        public string dys_wartosc { get; set; }
        public string grupa_nazwa { get; set; }
        public Nullable<bool> kart_wpis_rejestacja { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
    }
}
