//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Registration_Participant_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOneColumn
    {
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string dane { get; set; }
    }
}
