//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Registration_User_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PasswordTable()
        {
            this.UserTable = new HashSet<UserTable>();
        }
    
        public int pass_id { get; set; }
        public string pass_haslo { get; set; }
        public Nullable<System.DateTime> pass_data { get; set; }
        public string pass_haslo2 { get; set; }
        public Nullable<bool> pass_aktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTable> UserTable { get; set; }
    }
}
