//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abstract_And_Model_Layer.Registration_User_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int usesr_id { get; set; }
        public string user_login { get; set; }
        public string user_imie { get; set; }
        public string user_nazwisko { get; set; }
        public System.DateTime user_rejestracja { get; set; }
        public bool user_aktywny { get; set; }
        public Nullable<int> pass_id { get; set; }
    
        public virtual PasswordTable PasswordTable { get; set; }
    }
}
