
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibDatabase.DbContext
{

using System;
    using System.Collections.Generic;
    
public partial class kartoteka_TMP
{

    public int id { get; set; }

    public string imie { get; set; }

    public string nazwisko { get; set; }

    public string email { get; set; }

    public Nullable<System.DateTime> dataRej { get; set; }

    public Nullable<int> limitCzasu { get; set; }

    public Nullable<System.DateTime> dataKoncowa { get; set; }

    public Nullable<int> rejestracja { get; set; }

}

}
