
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibDatabase.DbContext
{

using System;
    using System.Collections.Generic;
    
public partial class kartoteka_2018
{

    public int kart_id { get; set; }

    public string kart_imie { get; set; }

    public string kart_imie2 { get; set; }

    public string kart_nazwisko { get; set; }

    public string kart_email { get; set; }

    public string kart_telefon { get; set; }

    public string kart_miejscowosc { get; set; }

    public string kart_ulica { get; set; }

    public string kart_nrDM { get; set; }

    public string kart_kodPocz { get; set; }

    public Nullable<bool> kart_aktywny { get; set; }

    public Nullable<int> zaw_id { get; set; }

    public string kart_pesel { get; set; }

    public Nullable<bool> kart_zgoda1 { get; set; }

    public Nullable<bool> kart_zgoda2 { get; set; }

    public Nullable<bool> kart_zgoda3 { get; set; }

    public string kart_uwagi { get; set; }

    public Nullable<int> dys_id { get; set; }

    public Nullable<int> plec_id { get; set; }

    public Nullable<int> kart_wiek { get; set; }

    public Nullable<int> kart_kod1 { get; set; }

    public Nullable<int> kart_kod2 { get; set; }

    public Nullable<System.DateTime> kart_data { get; set; }

    public Nullable<System.DateTime> kart_dataCzas { get; set; }

}

}
