
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibDatabase.DbContext
{

using System;
    using System.Collections.Generic;
    
public partial class kartoteka2
{

    public int kart_id { get; set; }

    public string kart_imie { get; set; }

    public string kart_nazwisko { get; set; }

    public string kart_email { get; set; }

    public string kart_telefon { get; set; }

    public string kart_uwagi { get; set; }

    public Nullable<int> plec_id { get; set; }

    public Nullable<int> dys_id { get; set; }

    public Nullable<int> grup_id { get; set; }

    public Nullable<System.DateTime> kart_dataUr { get; set; }

    public Nullable<System.DateTime> kart_dataRej { get; set; }

    public Nullable<bool> kart_wpis_rejestacja { get; set; }

    public Nullable<bool> kart_wpis_oplata { get; set; }

    public Nullable<bool> kart_wpis_rezerwowa { get; set; }



    public virtual Dystans Dystans { get; set; }

    public virtual grupa_kolarska grupa_kolarska { get; set; }

    public virtual Plec Plec { get; set; }

}

}
